# Generated by Django 3.1.4 on 2021-02-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marks_exams',
            name='english',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='marks_exams',
            name='history',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='marks_exams',
            name='russian',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
